### ISSUE TITLE
Feedback: Proposal

### ISSUE THREAD

**Issue by s-pangburn** [nicolauria/patter#1]
Hi Nico! Great work! Here's my feedback:

## Homepage
- [x] Your sidebar has an extra "Components" link that I think you forgot to remove?

## MVP List 
- [x] You should fix the formatting. [Make sure it looks like Bluebird!](https://github.com/appacademy/bluebird/wiki/mvp-list)

## Schema
- [x] Include your `belongs_to` and `has_many` associations!! (with backtick formatting and everything!)
- [x] Messages should probably have a `channel_id`, no?
- [x] Reconsider how you are doing direct messages. Will the current schema allow you to easily determine the ordering of messages?
   - It would probably be simpler to treat DMs as a special kind of channel? (either base the schema on the one for channels or use channels to implement DMs)

## Sample State
- [x] Put ```js at the top of your code block in Markdown to enable syntax highlighting!
- [x] **Don't include password digests or session tokens in the frontend state!** This is sensitive information and should only be stored in the database and cookies!
- [x] It's not clear how this maps to your backend for DMs, should probably be revised if you decide to redo how you're implementing them?

## Frontend Routes
- Looks good! No feedback :)

## Backend Routes
- All good here too! 

Try to address these as soon as possible so that you can hit the ground running tomorrow! Let me know if you need anything :)

**Comment by nicolauria** [comment]
Thanks for the feedback Stephen! I've made all the changes you suggested.

**Comment by s-pangburn** [comment]
Okay, looks good! Feel free to get started if you haven't yet 😄
