### ISSUE TITLE
Completed MVP 1 and 2

### ISSUE THREAD

**Issue by nicolauria** [nicolauria/patter#2]
Finished user auth and hosted site on Heroku
[https://patter-app.herokuapp.com](https://patter-app.herokuapp.com)
@s-pangburn

**Comment by s-pangburn** [comment]
Hey Nico! Excellent work! This is looking really solid so far.

Here's my feedback regarding user auth:

- [x] Your nav buttons (Login, Logout, and Signup) should darken slightly on hover. Just makes the site feel a little more interactive and alive.
- [x] The logo should also link to `/` in addition to the word "Patter". Right now only Patter links to root but not the logo.

And that's it! Great job handling those edge cases, I actually have no complaints :) Get these done and I'll mark this MVP as complete!

**Comment by nicolauria** [comment]
Hi Stephen. Thanks for the feedback. I've implemented the changes you suggested. Let me know what you think. @s-pangburn

**Comment by s-pangburn** [comment]
Hey Nico, thanks for implementing my feedback!

- [ ] The hover color-change is a little hard to see, since the shades are almost identical. Try a little lighter than that?

I'll mark this issue as closed as I really consider that more of a nitpick 🙂
